### ISSUE TITLE
Looking for a new owner

### ISSUE THREAD

**Issue by Morasiu** [astro-panda/Clockify.Net#70]
> TL;DR I'm seeking someone to transfer this repository and nuget package.

Hey!

I have been maintaining and developing Clockify.Net for over 4 years now. 

Since then API has changed so much that I can't keep up with the changes. I'm just tired of breaking changes and inconsistency. 

Now I'm looking for someone ready to take that burden from me. I've started large refactoring on `feature/cleanup` branch. You can continue it or choose your own path. 

I've found a few problems with Clockify API:

<details><summary>Paging</summary>
<p>

Sometimes it looks like this:
![image](https://user-images.githubusercontent.com/19236279/229303644-c82a4dc9-37b2-485d-9d2e-cf2984396ffd.png)

And sometimes it looks like this:
![image](https://user-images.githubusercontent.com/19236279/229303699-c60f12b7-a386-4949-bca0-4875cd71edba.png)

> Notice `sort` and `sort-column` name

</p>
</details> 

<details><summary>camelCase vs kebab-case</summary>
<p>

![image](https://user-images.githubusercontent.com/19236279/229303756-f32830ad-bdc6-433d-b711-a26cfcd6175c.png)
![image](https://user-images.githubusercontent.com/19236279/229303770-c1f9303f-ee20-4167-841a-57de7ac35d1a.png)

</p>
</details> 

And I can even find more.

## Contact

If you want to take this repo from me contact me here or on my email morasiu2@gmail.com

**Comment by Psypher9** [comment]
Hello! My team might be interested in taking this package over. What do you need from me?

**Comment by Morasiu** [comment]
Hi!

Thanks for taking an interest in the Clockify.Net library!

I will probably need:
* GitHub username or organization name to transfer repo
* Nuget username to add as Owner of a package.

We can do it by email here morasiu2@gmail.com

**Comment by eXpl0it3r** [comment]
Might want to update the ReadMe to remove the link this this issue 😉

**Comment by Psypher9** [comment]
Good point, thank you for that!

**Comment by Psypher9** [comment]
Taken care of!
